"""Acciones, condiciones y estados declarativos usados por PipeCraft.

El runtime único vive en :mod:`styler.runtime`; este paquete solo define las
piezas observables y validables que los grafos pueden reutilizar.
"""
from .actions import (
    Action,
    ActionContext,
    ActionResult,
    ConditionalAction,
    ForEachAction,
    FunctionAction,
    LaunchProcessAction,
    NoteAction,
    RetryAction,
    SequenceAction,
    SleepAction,
    StopProcessAction,
    TimeoutAction,
    TryFinallyAction,
    WaitAction,
    WithApplicationAction,
)
from .conditions import (
    AllCondition,
    AnyCondition,
    CallableCondition,
    CommandOutputCondition,
    Condition,
    ConditionAborted,
    ConditionState,
    CpuBelowCondition,
    DBusNameOwnedCondition,
    DirectoryQuiescentCondition,
    FileExistsCondition,
    FileStableCondition,
    GoneCondition,
    LatchedCondition,
    PathGlobCondition,
    ProcessAliveCondition,
    ProcessRunningCondition,
    StableValueCondition,
    WaitResult,
    WindowPresentCondition,
    evaluate_state,
    wait_until,
)
from .diagnostics import DiagnosticBundle, capture_wait_failure
from .specs import (
    ActionRegistry,
    ActionSpec,
    BuildContext,
    ConditionRegistry,
    ConditionSpec,
    SpecError,
    UnknownKindError,
    default_action_registry,
    default_condition_registry,
)
from .controller import ApplicationController, LaunchReadyReport
from .events import Event, EventBus, EventType
from .profiles import ApplicationProfile, callback_check
from .states import AppState, ApplicationStateMachine, InvalidTransition, TransitionRecord

__all__ = [
    "ActionRegistry",
    "ActionSpec",
    "BuildContext",
    "CommandOutputCondition",
    "ConditionRegistry",
    "ConditionSpec",
    "ConditionState",
    "ConditionalAction",
    "CpuBelowCondition",
    "DBusNameOwnedCondition",
    "DiagnosticBundle",
    "DirectoryQuiescentCondition",
    "FileStableCondition",
    "ForEachAction",
    "GoneCondition",
    "LatchedCondition",
    "NoteAction",
    "PathGlobCondition",
    "ProcessAliveCondition",
    "RetryAction",
    "SpecError",
    "StopProcessAction",
    "TimeoutAction",
    "TryFinallyAction",
    "UnknownKindError",
    "WindowPresentCondition",
    "WithApplicationAction",
    "capture_wait_failure",
    "default_action_registry",
    "default_condition_registry",
    "evaluate_state",
    "Action",
    "ActionContext",
    "ActionResult",
    "AllCondition",
    "AnyCondition",
    "AppState",
    "ApplicationController",
    "ApplicationProfile",
    "ApplicationStateMachine",
    "CallableCondition",
    "Condition",
    "ConditionAborted",
    "Event",
    "EventBus",
    "EventType",
    "FileExistsCondition",
    "FunctionAction",
    "InvalidTransition",
    "LaunchProcessAction",
    "LaunchReadyReport",
    "ProcessRunningCondition",
    "SequenceAction",
    "SleepAction",
    "StableValueCondition",
    "TransitionRecord",
    "WaitAction",
    "WaitResult",
    "callback_check",
    "wait_until",
]
