schema_version = 1

[components]
"app.gimp" = "applications/gimp.toml"
"app.photogimp" = "applications/photogimp.toml"
"app.vlc" = "applications/vlc.toml"
"app.konsole" = "applications/konsole.toml"
"app.dolphin" = "applications/dolphin.toml"
"desktop.kde.plasma" = "desktops/kde-plasma.toml"
"config.kde.user" = "configurations/kde-user-config.toml"
